### PR TITLE
fix namespace in memfun.hpp

### PR DESCRIPTION
**Pull request by user706**
Hi!

After having seen your code on codereview.stackexchange.com ([ref](https://codereview.stackexchange.com/q/14730)) I came across your generic repository.
Very nice code. (I think I can learn from your code!)

In this pull-request, there is a minor fix for memfun.hpp

How do you use your library, particularly with regard to delegates etc?
(I've worked out an example here: https://github.com/user706/code_generic/blob/master/code/code/main.cpp
Is this how you yourself would use your library, regarding mem_fun.hpp and forwarder.hpp?)

Thanks,
user706 ;)

### CODE REVIEW

**Comment by user706** [comment]
I've just added a commit, in which the missing functions for reference to **const** object and pointer to **const** object are added.
Also: I believe using defines makes this more readable to the human eye (allowing one to scan the differences in minimal lines)

**Comment by user706** [comment]
PS: I just realized that you actually have examples here [forwarder.cpp](https://github.com/user1095108/generic/blob/master/forwarder.cpp)!  (previously I had not looked into it, and thought it was part of a library)

How does one handle it your way, if one changes the code in forwarder.cpp to 
```cpp
struct S
{
  int f(int a) const noexcept
  {
    std::cout << a+1 << std::endl;
    return a+1;
  }
};
```
?

I'm somewhat confused about https://github.com/user1095108/generic/blob/master/forwarder.cpp#L17
because I thought that the template argument must be the signature of the member-function ([example](https://github.com/user706/code_generic/blob/master/code/code/main.cpp#L69))... but that's not the case in your example code.

Thanks

**Comment by user1095108** [comment]
Hello! So many comments. The library is part serious/part educational. I felt a sudden enthusiasm for C++ when I started writing it. The best "achievement" is probably the `callback.hpp` file, which allows one to implement efficient signal/slot mechanisms (check out the crl library to see how). `Forwarder.hpp `is mostly there for people too lazy to reimplement a stack-only `std::function`. Should you have any fixes, I'll merge them. I can even give you write access. But anyway, your question about forwarder touches on the famous trick of how to invoke member functions using `std::function` (or boost::function, its predecessor). You need to provide the function signature of the member function like `void()` in the example and then you invoke the forwarder instance with the object reference or pointer. This is then handled automagically by `std::invoke`, which recognizes a class reference/pointer and tries to invoke a member function.

**Comment by user706** [comment]
Ah ok thanks!

Here's a comparision of `std::function` and `gnr::forwarder`:
https://github.com/user706/code_generic/blob/master/code/intern/forwarder_ex1.cpp

There one has the following snippet
```cpp
// uncomment _one_ of the two lines below
template <typename T, std::size_t N = 0> using FF = std::function<T>;
//template <typename T, std::size_t N = default_size> using FF = gnr::forwarder<T, N>;
``` 
where `FF` will use `std::function`.

If one changes the snippet to
```cpp
// uncomment _one_ of the two lines below
//template <typename T, std::size_t N = 0> using FF = std::function<T>;
template <typename T, std::size_t N = default_size> using FF = gnr::forwarder<T, N>;
```
then `FF` will use `gnr::forwarder`.

**Comment by user1095108** [comment]
I fixed `memfun.hpp` and added an example `memfun.cpp`. `gdb` compiles the example to very concise code:

   0x0000000000000820 <+0>:	sub    $0x8,%rsp
   0x0000000000000824 <+4>:	callq  0x980 <S::f() const>
   0x0000000000000829 <+9>:	callq  0x980 <S::f() const>
   0x000000000000082e <+14>:	xor    %eax,%eax
   0x0000000000000830 <+16>:	add    $0x8,%rsp
   0x0000000000000834 <+20>:	retq

**Comment by user706** [comment]
Very nice!

Here's a benchmark: https://wandbox.org/permlink/IPfX4KqH39IWzUmx (alternatively in repo [here](https://github.com/user706/code_generic/tree/master/code/intern/memfun_benchmark))
`memfun` is much faster than calling `obj.*mem` or using `std::bind`

> 0x0000000000000820 <+0>: sub $0x8,%rsp
0x0000000000000824 <+4>: callq 0x980 <S::f() const>
0x0000000000000829 <+9>: callq 0x980 <S::f() const>
0x000000000000082e <+14>: xor %eax,%eax
0x0000000000000830 <+16>: add $0x8,%rsp
0x0000000000000834 <+20>: retq

PS: How did you generate that listing? (and how did you correlate it that that asm code corresponds to a call of a memfun object?)

**Comment by user1095108** [comment]
you can either use objdump or (preferrably) gdb (disass main).

2018-05-16 0:09 GMT+02:00 user706 <notifications@github.com>:

**Pull request merged**
